"""Seed data for the memory bank — run once to populate resolved_incidents and playbooks."""

SEED_RESOLVED_INCIDENTS = [
    {
        "id": "RI-001",
        "original_id": "INC-2847",
        "service": "payment-service",
        "severity": "P1",
        "category": "api_error.5xx",
        "causal_sig": "db_pool_exhausted",
        "outcome": "pool_resize",
        "resolved_in_min": 22,
        "confidence_score": 0.94,
        "playbook_summary": "Increased DB pool from 5→20, rolling restart",
        "resolution_path": [
            "Identified pool.max change in config diff",
            "Confirmed ConnectionPoolExhausted in logs",
            "Rolled back config to previous values",
            "Rolling restart of payment-service pods",
            "Error rate returned to baseline",
        ],
        "source_dataset": "seed",
    },
    {
        "id": "RI-002",
        "original_id": "INC-2201",
        "service": "payment-service",
        "severity": "P2",
        "category": "api_error.5xx",
        "causal_sig": "db_pool_exhausted",
        "outcome": "config_rollback",
        "resolved_in_min": 15,
        "confidence_score": 0.91,
        "playbook_summary": "Rolled back config change that reduced pool size",
        "resolution_path": [
            "Config push identified as root cause",
            "Rollback applied via kubectl",
            "Health checks passed within 2 minutes",
        ],
        "source_dataset": "seed",
    },
    {
        "id": "RI-003",
        "original_id": "INC-1803",
        "service": "order-service",
        "severity": "P1",
        "category": "api_error.5xx",
        "causal_sig": "db_pool_exhausted",
        "outcome": "pool_resize",
        "resolved_in_min": 18,
        "confidence_score": 0.89,
        "playbook_summary": "Same root cause on order-service, identical fix",
        "resolution_path": [
            "Identical pool exhaustion pattern on order-service",
            "Applied PB-001 playbook",
            "Resolved in 18 minutes",
        ],
        "source_dataset": "seed",
    },
    {
        "id": "RI-004",
        "original_id": "INC-2650",
        "service": "auth-service",
        "severity": "P2",
        "category": "config_push",
        "causal_sig": "bad_config_push",
        "outcome": "config_rollback",
        "resolved_in_min": 12,
        "confidence_score": 0.98,
        "playbook_summary": "JWT_SECRET missing after config deploy, rollback fixed it",
        "resolution_path": [
            "Auth service returning 401 on all requests",
            "Config diff showed JWT_SECRET removed",
            "Rollback to previous config version",
            "Service health restored",
        ],
        "source_dataset": "seed",
    },
    {
        "id": "RI-005",
        "original_id": "INC-2100",
        "service": "order-service",
        "severity": "P2",
        "category": "pod_oom_kill",
        "causal_sig": "pod_oom_kill",
        "outcome": "memory_limit_increase",
        "resolved_in_min": 8,
        "confidence_score": 0.95,
        "playbook_summary": "Increased memory limit from 512Mi to 1Gi",
        "resolution_path": [
            "Pods restarting every 3 minutes due to OOM",
            "Feature flag enabled in-memory cache without size limit",
            "Increased memory limit to 1Gi",
            "Stable after rollout",
        ],
        "source_dataset": "seed",
    },
    {
        "id": "RI-006",
        "original_id": "INC-1502",
        "service": "payment-service",
        "severity": "P2",
        "category": "latency_spike",
        "causal_sig": "downstream_timeout",
        "outcome": "manual_investigation",
        "resolved_in_min": 45,
        "confidence_score": 0.72,
        "playbook_summary": "Downstream dependency caused cascading timeouts",
        "resolution_path": [
            "Payment service latency spiked to 5s p95",
            "Traced to downstream fraud-check service",
            "Fraud-check service had DB connection issues",
            "Resolved after fraud-check team fixed their pool",
        ],
        "source_dataset": "seed",
    },
]

SEED_PLAYBOOKS = [
    {
        "playbook_id": "PB-001",
        "causal_sig": "db_pool_exhausted",
        "category": "api_error.5xx",
        "title": "DB Connection Pool Resize",
        "steps": [
            {"step": 1, "action": "Check current pool configuration", "command": "kubectl get configmap db-config -o yaml"},
            {"step": 2, "action": "Increase pool_size to 20 and max_idle to 10", "command": "kubectl edit configmap db-config"},
            {"step": 3, "action": "Rolling restart affected pods", "command": "kubectl rollout restart deployment/payment-service"},
            {"step": 4, "action": "Monitor error rate for 5 minutes", "command": None},
            {"step": 5, "action": "Verify connection pool metrics", "command": "curl prometheus/api/v1/query?query=db_pool_exhausted_total"},
        ],
        "success_rate": 0.96,
        "used_count": 47,
    },
    {
        "playbook_id": "PB-002",
        "causal_sig": "bad_config_push",
        "category": "config_push",
        "title": "Config Rollback",
        "steps": [
            {"step": 1, "action": "Identify last known good config version", "command": "kubectl get configmap --show-labels"},
            {"step": 2, "action": "Apply rollback", "command": "kubectl apply -f config-previous.yaml"},
            {"step": 3, "action": "Verify service health", "command": "curl -s https://service/health"},
            {"step": 4, "action": "Monitor for 5 minutes", "command": None},
        ],
        "success_rate": 0.99,
        "used_count": 23,
    },
    {
        "playbook_id": "PB-003",
        "causal_sig": "pod_oom_kill",
        "category": "pod_oom_kill",
        "title": "Pod Memory Limit Increase",
        "steps": [
            {"step": 1, "action": "Confirm OOM kill in events", "command": "kubectl describe pod <pod-name>"},
            {"step": 2, "action": "Increase memory limit in deployment", "command": "kubectl set resources deployment/<name> --limits=memory=1Gi"},
            {"step": 3, "action": "Watch rollout", "command": "kubectl rollout status deployment/<name>"},
        ],
        "success_rate": 0.94,
        "used_count": 31,
    },
]

SEED_INCIDENTS_RAW = [
    {
        "id": "RAW-001",
        "title": "Payment API 500 errors after deploy",
        "description": "Checkout returning 500 after v2.3.1 deploy",
        "service": "payment-service",
        "severity": "P1",
        "category": "api_error.5xx",
        "causal_sig": "db_pool_exhausted",
        "source_dataset": "seed",
    },
    {
        "id": "RAW-002",
        "title": "Auth service 401 after config push",
        "description": "All auth requests failing after config v1.4.3",
        "service": "auth-service",
        "severity": "P2",
        "category": "config_push",
        "causal_sig": "bad_config_push",
        "source_dataset": "seed",
    },
    {
        "id": "RAW-003",
        "title": "Order service OOM kill loop",
        "description": "Pods restarting every 3 minutes due to OOM",
        "service": "order-service",
        "severity": "P2",
        "category": "pod_oom_kill",
        "causal_sig": "pod_oom_kill",
        "source_dataset": "seed",
    },
]
